import Head from "next/head";
import { Inter } from "next/font/google";
import Calculator from "@/components/Calculator";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Calculator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <div className="App">
          <Calculator />
        </div>
      </main>
    </>
  );
}
